ERPLACE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from home.views import HomeListView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users_login.urls')),
    path('data/', include('alta_data.urls')),
    path('orders/', include('ordenes_servicio.urls')),    
    path('', login_required(HomeListView), name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

alta_data/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'alta_data'

urlpatterns = [
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Clientes ------------------------------------------------------
    path('clientes/', views.ClientsList.as_view(), name='clientes'),
    path('clients_detail/<int:id>/', views.ClientsDetail.as_view(), name = 'clients_detail'),
    path('clients-add/', views.ClientsCreate.as_view(),name='clients-add'),
    path('clients_update/<int:id>/', views.ClientsUpdate.as_view(), name='clients_update'),
    path('clients_delete/<int:id>/',views.ClientsDelete.as_view(), name='clients_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Certificado ------------------------------------------------------
    path('certificate/', views.CertificateList.as_view(), name='certificate'),
    path('certificate_detail/<int:id>/',views.CertificateDetail.as_view(), name='certificate_detail'),
    path('certificate-add/', views.CertificateCreate.as_view(),name='certificate-add'),
    path('certificate_update/<int:id>/', views.CertificateUpdate.as_view(), name='certificate_update'),
    path('certificate_delete/<int:id>/', views.CertificateDelete.as_view(), name='certificate_delete'),
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Certificado ------------------------------------------------------
    path('billing/', views.BillingList.as_view(), name='billing'),
    path('billing_detail/<int:id>/',views.BillingDetail.as_view(), name='billing_detail'),
    path('billing-add/', views.BillingCreate.as_view(),name='billing-add'),
    path('billing_update/<int:id>/', views.BillingUpdate.as_view(), name='billing_update'),
    path('billing_delete/<int:id>/', views.BillingDelete.as_view(), name='billing_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Certificado ------------------------------------------------------
    path('profile_contact/', views.ContactProfileList.as_view(),name='profile_contact'),
    path('profile_contact_detail/<int:id>/',views.ContactProfileDetail.as_view(), name='profile_contact_detail'),
    path('profile_contact-add/', views.ContactProfileCreate.as_view(),name='profile_contact-add'),
    path('profile_contact_update/<int:id>/', views.ContactProfileUpdate.as_view(), name='profile_contact_update'),
    path('profile_contact_delete/<int:id>/', views.ContactProfileDelete.as_view(), name='profile_contact_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Sitio ------------------------------------------------------
    path('profile_site/', views.SiteProfileList.as_view(),name='profile_site'),
    path('profile_site_detail/<int:id>/',views.SiteProfileDetail.as_view(), name='profile_site_detail'),
    path('profile_site-add/', views.SiteProfileCreate.as_view(),name='profile_site-add'),
    path('profile_site_update/<int:id>/', views.SiteProfileUpdate.as_view(), name='profile_site_update'),
    path('profile_site_delete/<int:id>/', views.SiteProfileDelete.as_view(), name='profile_site_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Instrumentos ------------------------------------------------------
    path('instruments/', views.InstrumentsList.as_view(),name='instruments'),
    path('instruments_detail/<int:id>/',views.InstrumentsDetail.as_view(), name='instruments_detail'),
    path('instruments-add/', views.InstrumentsCreate.as_view(),name='instruments-add'),   
    path('instruments_update/<int:id>/', views.InstrumentsUpdate.as_view(), name='instruments_update'),
    path('instruments_delete/<int:id>/', views.InstrumentsDelete.as_view(), name='instruments_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Instrumentos en Sitio------------------------------------------------------
    # path('instruments-site/', views.InstrumentsSiteList.as_view(),
    #      name='instruments-site'),
    # path('instruments-site/', views.InstrumentsSiteList.as_view(),name='instruments-site'),
    # path('instruments-site-add/', views.InstrumentsSiteCreate.as_view(),name='instruments-site-add'),
    # path('instruments-site_update/<int:id>/', views.InstrumentsSiteUpdate.as_view(), name='instruments-site_update'),
    # path('instruments_site_delete/<int:id>/', views.InstrumentsDelete.as_view(), name='instruments_site_delete'),
]

home/urls.py
from django.urls import path
from .views import HomeListView

urlpatterns = [
    path('', HomeListView.as_view(), name = 'home'),
]

ordenes_servicio/urls.py
from . import views
from django.urls import path

app_name = 'ordenes_servicio'

urlpatterns = [
    path('service_order/', views.ServiceOrderCreateView.as_view(), name= "OrdenServicio"),
    path('service_order_detail/<int:id>/', views.ServiceOrderDetailView.as_view(), name= "service_order_detail"),
    # path('service_order_update/<int:id>/', views.ServiceOrderUpdateView.as_view(), name= "service_order_update"),
    # path('service_order/', views.ServiceOrderCreateView.as_view(), name= "OrdenServicio"),
    # path('service_order_detail/<int:id>/', views.ServiceOrderDetailView.as_view(), name= "service_order_detail"),
    # path('service_order_update/<int:id>/', views.ServiceOrderUpdateView.as_view(), name= "service_order_update"),

    path('OS_PDF/<int:id>/', views.export_pdf, name="OS_PDF"),
    path('orden_servicio_list/', views.ServiceOrderList.as_view(), name='orden_servicio_list'),

]

users_login/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.conf import settings

from .forms import CustomPasswordReset, CustomPasswordSet
from .views import (
    Login,
    logoutUser,
    UserEditView
)

app_name = 'users_login'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', login_required(logoutUser), name='logout'),
    path('edit_profile/', UserEditView.as_view(), name="edit_profile"),

    #-----------------------------------------------------------------------------------------------

]

templates/principal/footer.html
<footer>
  <div class="layout3">
    Designed
    by
    <a href="https://www.linkedin.com/in/erick-serrato-garcia-57a672201/">
      Erick Serrato
    </a>
  </div>
</footer>

templates/principal/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/foundation.min.css' %}" />

  

<div class="top-bar" style="background-color: #111">
  <div class="top-bar-right">
    <ul class="menu" style="background-color: #111">
      <div class="dropdown" style="margin-right: 1rem">
        <button class="dropbtn">
          <i class="material-icons">
            <span class="material-icons-outlined"> save </span>
          </i>
          <span class="icon-text"> Registros </span>
        </button>

        <div class="dropdown-content">
          <a href="{% url  'alta_data:clientes' %}">Clientes</a>
          <a href="{% url 'alta_data:certificate' %}"
            >Perfiles de Certificado</a
          >
          <a href="{% url 'alta_data:billing' %}">Perfiles de Facturación</a>
          <a href="{% url 'alta_data:profile_contact' %}"
            >Perfiles de Contacto</a
          >
          <a href="{% url 'alta_data:profile_site' %}">Recolección y entrega</a>
          <a href="{% url 'alta_data:instruments' %}">Instrumentos</a>
        </div>
      </div>

      <div class="dropdown" style="margin-right: 3rem">
        <button class="dropbtn">
          <i class="material-icons">
            <span class="material-icons-outlined"> account_circle </span>
          </i>
          <span class="icon-text"> Cuenta </span>
        </button>
        <div class="dropdown-content">
          <a href="{% url 'users_login:edit_profile' %}">
            Configuracion de la cuenta
          </a>
          <a href="{% url 'users_login:logout' %}">Cerrar sesión</a>
        </div>
      </div>
    </ul>
  </div>
</div>

templates/principal/index.html
{% extends "../principal/layout.html" %} 
{% block title %} 
LACE | Página Principal 
{% endblock %} 
{% block body %}
<main>

    <h1>Bienvenido {{ user.first_name }} </h1>
    <p>
      <script>
        var meses = new Array(
          "Enero",
          "Febrero",
          "Marzo",
          "Abril",
          "Mayo",
          "Junio",
          "Julio",
          "Agosto",
          "Septiembre",
          "Octubre",
          "Noviembre",
          "Diciembre"
        );

        var diasSemana = new Array(
          "Domingo",
          "Lunes",
          "Martes",
          "Miércoles",
          "Jueves",
          "Viernes",
          "Sábado"
        );

        var f = new Date();
        document.write(
          diasSemana[f.getDay()] +
            ", " +
            f.getDate() +
            " de " +
            meses[f.getMonth()] +
            " de " +
            f.getFullYear()
        );
      </script>
    </p>

<div class="dash-board-index" >

    <div class="callout warning index1">
      <h5>Avisos Generales</h5>
      <p>Recuerda cerrar sesión al retirarte</p>
      <li>Anuncio 1 </li>
      <li>Anuncio 2 </li>
      <li>Anuncio 3 </li>
    </div>

    <div class="callout primary index2">
      <h5>  Pendientes </h5>
      <p>Este es tu listado de pendientes en esta semana.</p>
      <li> Pendiente 1 </li>
      <li>Pendiente 2 </li>
      <li>Pendiente 3 </li>
    </div>

</div>

</main>
{% endblock %} 

{% block extrajs %} 

{% endblock extrajs %}

templates/principal/layout.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %} {% endblock %}</title>
    {% block head %} {% endblock %}
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;500&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}" />
    <link rel="stylesheet" href="{% static 'css/globales.css' %}" />
    <link rel="stylesheet" href="{% static 'css/grids.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/buttons-navs-dropdowns.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />
   <link rel="stylesheet" href="{% static 'css/tablas.css' %}" />

   <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>


   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>   
   <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script>
   $(document).ready(function()
   {
      $('#id_id_empresa').select2();
   }
   ) ;

</script>




   
    {% block extra_css %} {% endblock extra_css %}




  </head>

  <body>
    <main>
      {% include 'principal/header.html' %}

      <!-- comienza menú lateral colapsable -->
      <div
        id="mySidebar"
        class="sidebar"
        onmouseover="toggleSidebar()"
        onmouseout="toggleSidebar()"
      >
        <br />
        <a href="{% url 'home' %}">
          <i class="material-icons"> &#xE88A; </i>
          <span class="icon-text"> Inicio </span>
        </a>
        <hr class="hr-principal" />

        <a href="{% url 'ordenes_servicio:OrdenServicio' %}">
          <i class="material-icons"> send_and_archive </i>
          <span class="icon-text">Crear OS</span>
        </a>

        <a href="{% url 'ordenes_servicio:orden_servicio_list' %}">
          <i class="material-icons"> fact_check </i>
          <span class="icon-text">Lista OS</span>
        </a>

        <hr class="hr-secundario" />
      </div>
      <!-- termina menú lateral colapsable -->
      <div id="main">{% block body %} {% endblock body %}</div>

      {% include 'principal/footer.html' %} 
      {% block extrajs %} 
      {% endblock extrajs %}
    </main>
  </body>

  <script src='{% static "js/principal/layout.js" %}'></script>
  <script src='{% static "js/foundation.min.js" %}'></script>
  <script src='{% static "js/tablas/jquery.js" %}'></script>
  <script src='{% static "js/tablas/jquery_dataTables.js" %}'></script>
  <script src='{% static "js/tablas/dataTables_bootstrap.js" %}'></script>
  <script src='{% static "js/tablas/moment.js" %}'></script>
  <script src='{% static "js/tablas/filtro_busqueda.js" %}'></script>
  <script src='{% static "js/formularios/formularios.js" %}'></script>
</html>