ERPLACE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from home.views import HomeListView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users_login.urls')),
    path('data/', include('alta_data.urls')),
    path('orders/', include('ordenes_servicio.urls')),    
    path('', login_required(HomeListView), name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomeListView

urlpatterns = [
    path('', HomeListView.as_view(), name = 'home'),
]

ordenes_servicio/urls.py
from . import views
from django.urls import path

app_name = 'ordenes_servicio'

urlpatterns = [
    path('service_order/', views.ServiceOrderCreateView.as_view(), name= "OrdenServicio"),
    path('service_order_detail/<int:id>/', views.ServiceOrderDetailView.as_view(), name= "service_order_detail"),
    # path('service_order_update/<int:id>/', views.ServiceOrderUpdateView.as_view(), name= "service_order_update"),
    # path('service_order/', views.ServiceOrderCreateView.as_view(), name= "OrdenServicio"),
    # path('service_order_detail/<int:id>/', views.ServiceOrderDetailView.as_view(), name= "service_order_detail"),
    # path('service_order_update/<int:id>/', views.ServiceOrderUpdateView.as_view(), name= "service_order_update"),

    path('OS_PDF/<int:id>/', views.export_pdf, name="OS_PDF"),
    path('orden_servicio_list/', views.ServiceOrderList.as_view(), name='orden_servicio_list'),

]

ordenes_servicio/models.py
from django.db import models

# Create your models here.

ordenes_servicio/views.py
import json
import dateutil.parser as formatdate
from django.shortcuts import render
from django.urls import reverse
from ordenes_servicio import forms as form_app
from lace_app import models as models_app
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from formtools.wizard.views import SessionWizardView
from django.http import HttpResponse
# para generar PDF se necesita lo siguiente:
from django.template.loader import render_to_string, get_template
from weasyprint import HTML
from weasyprint.fonts import FontConfiguration
import django.views.generic as views
from lace_app.models import(
    InstrumentosImagen,
    OrdenServicio,
    Facturacion,
)
from alta_data import forms as ad_forms
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

#-------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------------- Orden de Servicio ----------------------------------------------------------
#--------------------------------------------------------- Lista ---------------------------------------------------------------
class ServiceOrderList(ListView):
    model = OrdenServicio
    template_name = 'ordenes_servicio/service_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ordenes'] = OrdenServicio.objects.all()

        return context
#-------------------------------------------------------- Creación -------------------------------------------------------------
#---------------------------------------------------- Test 2 ---------------------------------------------------------------------
class ServiceOrderCreateView(views.FormView):
    # template_name = "../templates/ordenes_servicio/old_service_order_create.html"
    template_name = "../templates/ordenes_servicio/service_order_create.html"
    form_class = form_app.OSFormulario1
    form_list = [
        [[form_class,form_app.OSFormulario9], form_app.OSFormulario2, form_app.OSFormulario3, form_app.OSFormulario4, form_app.OSFormulario5],
        [form_app.OSFormulario6],[[form_app.OSFormulario7, form_app.OSFormulario8]],[form_app.OSFormulario9],
        ]
    paso = None
    sub_paso = None
    success_url = reverse_lazy('ordenes_servicio:orden_servicio_list')

    def post(self, request, *args, **kwargs):
        """Controla el flujo del código según las peticiones en el objeto 'request'"""
        if request.POST.get("servicio") == "detalles":
            objeto = self.get_objects(request)
            return HttpResponse(objeto)
        elif request.POST.get("servicio") == "formulario":
            formulario = self.get_forms(request)
            return HttpResponse(formulario)
        elif request.POST.get("servicio") == "crear":
            request_crear = self.create_object(request)
            return HttpResponse(request_crear)
        elif request.POST.get("servicio") == "actualizar":
            if request.POST.get("valor"):
                request_actualizar = self.update_object(request)
            else:
                request_actualizar = self.update_db(request)
            return HttpResponse(request_actualizar)
        else:
            flow_control = self.step_checker(request)
            if flow_control.get('ajax'):
                context = self.get_context_data(form= self.form_list)
                return HttpResponse(json.dumps(context))
            else:
                return super().post(request)

    def get(self, request, *args, **kwargs):
        self.step_checker(request)

        if self.paso == 1:
            context = self.get_context_data(form= self.form_list)

        return render(request, self.template_name, context= context)

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(**kwargs)
        new_context = {}
        new_context['paso'] = self.paso
        new_context['sub_paso'] = self.sub_paso
        new_context['id_parent'] = self.request.POST.get('id_parent')

        if self.paso == 1:
            if self.sub_paso == 1:
                print(self.forms_dict())
                new_context['form_list'] = self.forms_dict()
            if self.sub_paso == 2:
                form = self.forms_dict()
                new_context['html'] = self.formatting(
                    render_to_string(
                        '../templates/ordenes_servicio/OSForms_templates/form_2.html', context= form
                        ))
                new_context['html_extra'] = self.formatting(
                    render_to_string(
                        '../templates/ordenes_servicio/OSForms_templates/form_5.html', context= form
                    ))
            if self.sub_paso == 3:
                form = self.forms_dict()
                new_context['html'] = self.formatting(
                    render_to_string(
                        '../templates/ordenes_servicio/OSForms_templates/form_2.html', context= form
                        ))
        elif self.paso == 2:
            form = self.forms_dict()
            parent = self.request.POST.get('id_empresa')
            instrument_list = models_app.Instrumento.objects.filter(id_empresa= int(parent))
            html_name = form.get('SubservicioForm2').fields['id_instrumento'].widget.attrs['id']
            name_list = "listado_" + str(self.request.POST.get("id_parent"))
            id_table = "instrument_table_" + html_name.split("_")[-1]
            html_list = {}
            html_list['certificado'] = self.formatting(
                render_to_string(
                    '../templates/ordenes_servicio/OSForms_templates/form_3.html', context= {"form": form, "list": name_list, "control": "certificado"}
                ))
            html_list['facturacion'] = self.formatting(
                render_to_string(
                    '../templates/ordenes_servicio/OSForms_templates/form_3.html', context= {"form": form, "list": name_list, "control": "facturacion"}
                ))
            html_list['instrumentos'] = self.formatting(
                render_to_string(
                    '../templates/ordenes_servicio/OSForms_templates/form_3.html', context= {"form": form, "list": name_list, "control": "instrumento", "html_name": html_name}
                ))
            html_list['lista_instrumentos'] = self.formatting(
                render_to_string(
                    '../templates/ordenes_servicio/OSForms_templates/form_3.html', context= {"id": html_name, "list": name_list, "object_list": instrument_list, "control": "instrumento_lista", "html_name": html_name[3:], "id_table": id_table}
                ))
            html_list['id_table'] = id_table
            new_context['html'] = html_list

        elif self.paso == 3:
            form = self.forms_dict()
            new_context['instrument'] = self.request.POST.get('posicion')
            new_context['html'] = self.formatting(
                render_to_string(
                    '../templates/ordenes_servicio/OSForms_templates/form_4.html', context= form
                )
            )
        elif self.paso == 4:
            form = self.forms_dict()
            new_context['html'] = self.formatting(
                render_to_string(
                    '../templates/ordenes_servicio/OSForms_templates/form_5.html', context = form
                )
            )
        return new_context

    def form_valid(self, form):
        print(self.request.POST)
        meta_data = self.request.POST

        if form.is_valid():
            sub_servicios = int(meta_data.get("sub_servicios_total"))
            sub_serv_list = []
            #Campos necesarios para crear objeto OrdenServicio
            obj_os = self.ordenServicioObjeto(meta_data)
            #Campos necesarios para crear objeto SubServicio
            for sub_servicio in range(sub_servicios):
                obj_subserv = self.subServicioObjeto(meta_data, sub_servicio)
                sub_serv_list.append(obj_subserv)
                #Campos necesarios para crear objeto InstrumentOS
                instrumentos = int(len(meta_data.get("id_instrumento_{}".format(sub_servicio)))/2);
                obj_instrumentOS = []
                for item in range(instrumentos):

                    obj_instrumentOS.append(self.instrumentOSObjeto(meta_data, obj_subserv, sub_servicio, item))
                    #Campos necesarios para crear objeto Fotografia
                    total_img = int(meta_data.get("TOTAL_images_{}_{}".format(sub_servicio, item)))
                    obj_foto = []
                    for img in range(total_img):
                        obj_foto.append(self.fotografiaObjeto(sub_servicio, item, img))
                    #Adjuntando fotografías
                    for foto in obj_foto:
                        obj_instrumentOS[-1].id_imagen.add(foto)
                #Campos necesarios para crear objeto ServicioSitio
                obj_sitio = self.tipoSitioObjeto(meta_data, obj_os, sub_servicio)
                #Agregando subservicios a OS
                for subserv in sub_serv_list:
                    obj_os.id_subservicio.add(subserv)

        return HttpResponse(json.dumps({"status": 248, "url": self.get_success_url()}))
    
    def ordenServicioObjeto(self, meta_data):
        #Campos necesarios para crear objeto OrdenServicio
        id_cliente = meta_data.get('id_cliente')
        # servicioContratado = meta_data.get('servicioContratado')
        id_contacto = meta_data.get('id_contacto')
        dia_servicio = meta_data.get('dia_servicio')
        observaciones_os = meta_data.get('observaciones_os')
        
        cliente = models_app.ClienteEmpresa.objects.get(id= int(id_cliente))
        contacto = models_app.Contacto.objects.get(id= int(id_contacto))
        estatus = models_app.Estatus.objects.get(id= 1)

templates/ordenes_servicio/OS_PDF.html
{% load static %}
<!DOCTYPE html>
<html lang="es" xml:lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge" /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OS-PDF</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>

       @page {
       /*  size: letter landscape; */  /* Documento "horizontal" */
        margin: 1.5cm 1.5cm 3.5cm 1.5cm;
      } 


      html {

      }

  body {
    width: 100% ;
    text-transform: uppercase;
    height: 100%;
    background: white;
    color: black;
    font-size: 100%;
    -webkit-font-smoothing: antialiased;
    -webkit-text-size-adjust: none;
  }

      .header {
        text-align: center;
        font-weight: bold;
      }
      /* Separamos las tablas en div para usar las propiedades del Flexbox*/
      .contenedor {
        display: flex;
        flex-direction: column;
      }

  .OS {
    font-size: 100%;
    font-weight: bold;
    border: black 1px solid;
  }

      /* Damos formato a las tablas así como a sus elementos*/
      table {
        width: 100%;
        border-collapse: collapse;
        border: black 1px solid;
        font-weight: normal;
      }

      th {
        font-size: 60%;
        font-weight: bold;
        border: black 1px solid;
        height: 15;
        text-align: center;
      }

      td {
        font-size: 60%;
        font-weight: bold;
        border: black 1px solid;
        height: 20;
        text-align: center;
      }
      .separacion {
        font-size: 10%;
        font-weight: bold;
        border: black 1px solid;
        height: 7;
      }


      .head {
        font-size: 70%;
        font-weight: bold;
        border: black 1px solid;
      }




    </style>
  </head>

  <body>

    <p class="header">
          <img src="{% static 'images/logo.png' %}"> <br>
      LACE LABORATORIOS DE CALIBRACI&Oacute;N S.A. DE C.V <br />
      Sistema de gesti&oacute;n de calidad basado en NMX-EC-17025-IMNC-2018
      <br />
      Calibraci&oacute;n, sin&oacute;nimo de calidad.
    </p>
    <table>
      <tr>
        <th colspan="4" class="OS"> <p>ORDEN DE SERVICIO</p> </th>
      </tr>
    </table>
   <br>
    <table>
      <tr>
        <td>
          <p>F. RECEPCI&Oacute;N:&nbsp;&nbsp;</p>
        </td>
        <td><p>F. ENTREGA:&nbsp;&nbsp;---------</p></td>
        <td>
        <p>
        NÚMERO DE CLIENTE:&nbsp;&nbsp;<br> 
        L - {{orden.id_facturacion.id_empresa.id_empresa}} - {{orden.id_facturacion.id_csucursal.id_CSucursal}}
        </p>
       </td>
        <td>
          <p>ORDEN DE SERVICIO:&nbsp;&nbsp;------------------</p>
        </td>
      </tr>
    </table>

<br>
    <table>
      <tr>
        <th colspan="4" class="OS"> <p>DATOS DE FACTURACIÓN</p> </th>
      </tr>
      <tr>
        <td><p>RAZ&Oacute;N SOCIAL:&nbsp;&nbsp;{{orden.id_facturacion.id_empresa.razonsocial}}</p></td>
        <td colspan="2"><p>RFC:&nbsp;&nbsp;{{orden.id_facturacion.rfc}}</p></td>
        <td><p>PERSONA:&nbsp;&nbsp;{{orden.id_facturacion.tipopersona}}</p></td>
      </tr>

      <tr>
        <td rowspan="3"><p>DIRECCI&Oacute;N</p></td>
        <td><p>CALLE:&nbsp;&nbsp;{{orden.id_facturacion.calle}}</p></td>
        <td><p>N&#176; EXT:&nbsp;&nbsp;{{orden.id_facturacion.noext}}</p></td>
        <td><p>N&#176; INT:&nbsp;&nbsp;{{orden.id_facturacion.noint}}</p></td>
      </tr>

      <tr>
        <td><p>COL:&nbsp;&nbsp;{{orden.id_facturacion.colonia}}</p></td>
        <td><p>ALCALD. O MUN.:&nbsp;&nbsp;{{orden.id_facturacion.alcaldia_municipio}}</p></td>
        <td><p>C.P.:&nbsp;&nbsp;{{orden.id_facturacion.codigopostal}}</p></td>
      </tr>
      <tr>
        <td><p>ESTADO:&nbsp;&nbsp;{{orden.id_facturacion.entidadfed}}</p></td>
        <td><p>PA&Iacute;S:&nbsp;&nbsp;{{orden.id_facturacion.pais}}</p></td>
        <td><p>EMAIL:&nbsp;&nbsp;{{orden.id_facturacion.email}}</p></td>
      </tr>
      <tr>
        <td colspan="2">
          <p>M&Eacute;TODO DE PAGO:&nbsp;&nbsp;{{orden.id_facturacion.metodopago}}</p>
        </td>
        <td><p>FORMA DE PAGO:&nbsp;&nbsp;{{orden.id_facturacion.formapago}}</p></td>
        <td><p>USO DE CDFI:&nbsp;&nbsp;{{orden.id_facturacion.usocfdi}}</p></td>
      </tr>
    </table>
<br>
    <table>
      <tr>
        <th class="OS">SERVICIO</th>
      </tr>
    </table>
  <br />

    <table>
        <thead>
      <tr>
        <th>
            CERTIFICADO/ <br />
            SOLICITANTE
        </th>
        <th><p>SITIO</p></th>
        <th>
          <p>
            Servicio <br>
            requerido
          </p>
        </th>

        <th>
          <p>
            área
          </p>
        </th>
        <th>
          <p>
            CLAVE DEL <br />
            INSTRUMENTO
          </p>
        </th>
      </tr>
      </thead>

      {% for subservicio in orden.id_subservicio.all%}
      <tbody>
      <tr>
        <td>
          <p>{{subservicio.id_certificado}}</p>
        </td>
        <td>
          <p>{{subservicio.id_sitio}}</p>
        </td>
        <td>
          <p>servicio </p>
        </td>
        <td>
          <p>Area/magnitud </p>
        </td>
         
        <td> 
            {% for instrumento in subservicio.id_instrumento.all%}
          <p>{{instrumento}} </p>
            {% endfor %}
        </td>
      </tr>
      </tbody>

        {% endfor %}
    </table>
  <br />


  


  </body>
</html>

templates/ordenes_servicio/old_service_order_create.html
{% extends "principal/layout.html" %}
{% load i18n %}
{% load static %}

{% block title %} 
LACE | Orden de Servicio
{% endblock %} 

{% block head %}
    {{ wizard.form.media }}
{% endblock %}

{% block extra_css %}
    <style>
        .form-content {
            display: flex;
            flex-direction: column;
            align-items: start;
            justify-content: space-around;
            margin: 1rem;
        }
        .form-content flex-column{
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            gap: 1rem;
        }
        .step_2 {
            flex-direction: column;
            width: 50rem;
        }
        .field-set ul {
            list-style-type: none;
            padding: 0;
            margin: 1rem;
        }
        .flex-content-row {
            display: flex;
            flex-direction: row;
            justify-content: center;
        }
        .icon-content:nth-child(1){
            margin: 0.5rem 1rem 0.5rem 0;
        }
        .icon-content:nth-child(2){
            margin: 0.5rem 0 0.5rem 1rem;
        }
        .icon {
            border: none;
            background-color: transparent;
        }
        .icon:hover{
            cursor: pointer;
            -webkit-transform: scale(1.2);
            transform: scale(1.2);
        }
        .center{
            display: flex;
            flex-direction: row;
            justify-content: center;
        }
        #minus-button {
            display: none;
        }
        .colapsar {
            background-color: #777;
            color: white;
            cursor: pointer;
            padding: 1rem;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
        }
        .active, .colapsar:hover {
            background-color: #555;
        }
        .colapsar:after {
            content: '\002B';
            color: white;
            font-weight: bold;
            float: right;
            margin-left: 5px;
        }
        .active:after {
            content: "\2212";
        }
        .content {
            padding: 0 18px;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
            background-color: #f1f1f1;
        }
        .billing-content,
        .services-content {
            padding-bottom: 1.5rem;
            border-bottom: thistle solid 0.1rem;
        }
        .site .content,
        .certified .content,
        .content-element {
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-template-rows: repeat(7, 1fr);
            gap: 0.5rem;
        }
        .subservice-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 0.3rem;
        }
        .instrument {
            grid-column: 1 / 3;
        }
        .instrument-content {
            display: grid;
            grid-template-columns: 2fr 1fr;
            grid-template-rows: 90% 20%;
            gap: 0.3rem;
            margin: 1rem;
        }
        .div-button {
            grid-column: 1 / 3;
            justify-self: center;
        }
        .billing-button {
            display: flex;
            justify-content: center;
        }
        .element-head {
            font-weight: bold;
            text-align: right;
        }
        .element-data {
            text-align: left;
            max-width: 66.66%;
        }
    </style>
{% endblock extra_css %}

{% block body %}
    <h1>Generar Orden de Servicio:</h1>
    <div class="contenedo_formularios">
        <form action="#" method="POST" id= "id_formulario_OS" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="paso_formulario" id= "id_paso_formulario" value= "{{ paso }}">
            <input type="hidden" name="sub_paso_formulario" id= "id_sub_paso_formulario" value= "{{ sub_paso }}">            
            <input type="hidden" name="image_total_form" id= "image_total_form" value= "2">

            <div id="id_paso_1">
                <p>Paso 1: Seleccione el lugar y el tipo de servicio</p>
                <div class="ordenServicio-form">
                    {{ form_list.OrdenServicioForm.id_cliente.label_tag }}
                    {{ form_list.OrdenServicioForm.id_cliente }}
                </div>
            </div>
            <div id="id_paso_2" style= "display:none;">
                <input type="button" value="Agregar otro servicio" id="multiplicar">
                {{ form_list.OrdenServicioForm.servicioContratado.label_tag }}
                {{ form_list.OrdenServicioForm.servicioContratado}}
            <div id= "id_paso_2_sitio"></div>
            <div id= "id_paso_2_servicio"></div>
            <input type="button" id= "enviar-paso-1" value= "Siguiente Paso" disabled>
            </div>
            <!-- <p>Paso 2: Seleccione los instrumentos, datos relacionados a certificado y facturación.</p> -->
            <div id="id_paso_3"></div>
            <!-- <p>Paso 3: Seleccione los servicios a realizar para los instrumentos</p> -->
            <div id="id_paso_4"></div>
            <!-- <p>Paso 4: Seleccione día para servicio, datos de solicitante (contacto) y observaciones generales.</p> -->
            <div id="id_paso_5"></div>
        </form>
    </div>
{% endblock %}

{% block extrajs %}
    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        const django_variables = {
            token: '{{ csrf_token }}',
            // sitiosLista: '{{ sitios_lista }}',
        }
    </script>
    <script src= "{% static 'js/apps/orden_servicio.js' %}"></script>
    <script>
        // var optionCU = document.querySelector("#OptionCU_0").value;
        // var control;

        // if (optionCU == "0") {
        //     control = document.querySelector("#id_service_order_create_view-current_step");
        //     if (control.value != 0) {
        //         document.querySelector("#control-formulario").style.display = "none";
        //     }
        // } else {
        //     control = document.querySelector("#id_service_order_update_view-current_step");

        //     if (control.value == "0") {
        //         formConstructor();
        //     } else {
        //         document.querySelector("#control-formulario").style.display = "none";  
        //     }
        // }
        // function addInput() {
        //     var forms = document.querySelector('#id_0-TOTAL_FORMS');
        //     var instruments = document.querySelector("#id_0-0-id_instrumento").cloneNode(true);
            
        //     instruments.id = "id_0-" + forms.value + "-id_instrumento";
        //     console.log(instruments);
            
        //     for (var i=0; i < instruments.children.length; i++) {
        //         var one_instr = instruments.children[i].firstChild;
        //         one_instr.htmlFor = "id_0-" + forms.value + "-id_instrumento_" + i;
        //         one_instr.firstChild.id = "id_0-" + forms.value + "-id_instrumento_" + i;
        //         one_instr.firstChild.name = "0-" + forms.value + "-id_instrumento";
        //     }

        //     var div = document.createElement("div");
        //     div.classList = "form-content field-content";
        //     div.id = "div-target-" + forms.value;
        //     document.querySelector("#div-tar").appendChild(div);

        //     var tags = [['fieldset', 'field-set', 'legend', 'Instrumentos'], ['-id_sitio', 'Datos de Sitio'],['-id_certificado','Datos de Certificado']];
        //     var list_elements = elementCreate(tags, forms.value, instruments);

        //     var div_inner = list_elements.forEach((element,index) => {
        //         var div_inner = document.createElement("div");
        //         div_inner.classList = 'flex-column field-content';
        //         if (index == 0) {
        //             div_inner.appendChild(element);
        //         } else {
        //             element.forEach((item) => div_inner.appendChild(item));
        //         }
        //         div.appendChild(div_inner);
        //     })
        //     forms.value = parseInt(forms.value) + 1;
        //     if (forms.value > 1) {
        //         document.getElementById('minus-button').style.display= "block";
        //     };
        // }

        // function deleteInput() {
        //         var forms = document.querySelector('#id_0-TOTAL_FORMS');
        //         forms.value = parseInt(forms.value) - 1;
        //         removeDiv = '#div-target-'+forms.value;
                
        //         document.querySelector(removeDiv).remove();

        //         if (forms.value < 2) {
        //             document.getElementById('minus-button').style.display= "none";
        //         };
        // }
        // function otherDeleteInput() {
        //         var forms = document.querySelector('#id_0-TOTAL_FORMS');
        //         forms.value = parseInt(forms.value) - 1;
        //         removeDiv = '#div-target-0';

        //         var div_del = document.querySelectorAll(removeDiv);
        //         div_del[div_del.length - 1].remove();

        //         if (forms.value < 2) {
        //             document.getElementById('minus-button').style.display= "none";
        //         };
        // }

        // function elementCreate(lista, forms_value, instruments) {
        //     var ret_ele = [];

        //     for (var i= 0; i <= lista.length - 1; i++) {
        //         var element = lista[i];

        //         if (i == 0) {
        //             var fieldinstrument = document.createElement(element[0]);
        //             fieldinstrument.classList = element[1];
        //             var legend_instr = document.createElement(element[2]);
        //             legend_instr.innerHTML = element[3];
        //             fieldinstrument.appendChild(legend_instr);
        //             fieldinstrument.appendChild(instruments);
        //             new_element = fieldinstrument;
        //         } else {
        //             var new_input = document.querySelector("#id_0-0" + element[0]).cloneNode(true);
        //             new_input.name = "0-" + forms_value + element[0];
        //             new_input.id = "id_0-" + forms_value + element[0];
        //             var new_label = document.createElement("label");
        //             new_label.innerHTML = element[1];
        //             new_label.htmlFor = new_input.id;
        //             new_element = [new_label, new_input]
        //         }
        //         ret_ele.push(new_element);
        //     }
        //     return ret_ele
        // }
        // function formConstructor() {
        //     var optionCU = document.querySelector("#OptionCU_0").value;
        //     var forms = document.querySelector('#id_0-TOTAL_FORMS').value;

        //     if(optionCU == "1") {
        //         var total_forms = document.querySelector("#ServicesNum_0").value - 1;

        //         if(forms > 1) {
        //             otherDeleteInput();
        //         }
        //     }
        // }
    </script>
{% endblock %}

templates/ordenes_servicio/service_order.html
{% extends "../principal/layout.html" %} 
{% block title %} 
LACE | Ordenes de Servicio
{% endblock %} 
{% block body %}
<main>
  <h1>Ordenes de Servicio</h1>
  <section class="sombra">
    <h3>Listado de registro</h3>
    <section class="sombra ">
      <div class="row">
        <div class="container"> 
            <table id="sort">
              <thead>
                <tr>
                  <th>Detalles</th>
                  <th class="sort-head">ID Cliente</th>
                  <th class="sort-head">ID Orden Servicio</th>
                  <th class="sort-head">Estatus</th>
                </tr>
              </thead>
              <tbody>
                {% if ordenes %} 
                  {% for orden in ordenes %}
                    <tr>
                      <td>
                        <div class="dropdown button-position">
                          <button class="button2 ">
                            <i class="material-icons">
                              <span class="material-icons-outlined"> settings </span>
                            </i>
                            <span class="icon-text"> Opciones </span>
                          </button>
                  
                          <div class="dropdown-content" style="margin-top: 10rem;margin-left: 0rem;">
                            <a href="{% url 'ordenes_servicio:service_order_detail' orden.id %}">Detalles</a>
                            <a href="#">Actualizar</a>
                            <a href="#">Eliminar</a>
                          </div>
                        </div>
                      </td>
                      <td>{{ orden.id_cliente }}</td>
                      <td>{{ orden.id_orden }}</td>
                      <td>{{ orden.estatus }}</td>
                    </tr>
                  {% endfor%}
              </tbody>
                <!-- If objet_list is empty  -->
                {% else %}
                  <p style="color: red">No tienes perfiles de clientes</p>
                {% endif %}
            </table>
              <nav style="display: flex; justify-content: center">
                <a
                  href="{% url 'ordenes_servicio:OrdenServicio' %}"
                  class="button1 button-position"
                  >Crear Nueva OS</a
                >
              </nav>
          </div>
        </div>
    </section>
</main>

{% endblock %}