ERPLACE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from home.views import HomeListView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users_login.urls')),
    path('data/', include('alta_data.urls')),
    path('orders/', include('ordenes_servicio.urls')),    
    path('', login_required(HomeListView), name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

alta_data/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'alta_data'

urlpatterns = [
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Clientes ------------------------------------------------------
    path('clientes/', views.ClientsList.as_view(), name='clientes'),
    path('clients_detail/<int:id>/', views.ClientsDetail.as_view(), name = 'clients_detail'),
    path('clients-add/', views.ClientsCreate.as_view(),name='clients-add'),
    path('clients_update/<int:id>/', views.ClientsUpdate.as_view(), name='clients_update'),
    path('clients_delete/<int:id>/',views.ClientsDelete.as_view(), name='clients_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Certificado ------------------------------------------------------
    path('certificate/', views.CertificateList.as_view(), name='certificate'),
    path('certificate_detail/<int:id>/',views.CertificateDetail.as_view(), name='certificate_detail'),
    path('certificate-add/', views.CertificateCreate.as_view(),name='certificate-add'),
    path('certificate_update/<int:id>/', views.CertificateUpdate.as_view(), name='certificate_update'),
    path('certificate_delete/<int:id>/', views.CertificateDelete.as_view(), name='certificate_delete'),
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Certificado ------------------------------------------------------
    path('billing/', views.BillingList.as_view(), name='billing'),
    path('billing_detail/<int:id>/',views.BillingDetail.as_view(), name='billing_detail'),
    path('billing-add/', views.BillingCreate.as_view(),name='billing-add'),
    path('billing_update/<int:id>/', views.BillingUpdate.as_view(), name='billing_update'),
    path('billing_delete/<int:id>/', views.BillingDelete.as_view(), name='billing_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Certificado ------------------------------------------------------
    path('profile_contact/', views.ContactProfileList.as_view(),name='profile_contact'),
    path('profile_contact_detail/<int:id>/',views.ContactProfileDetail.as_view(), name='profile_contact_detail'),
    path('profile_contact-add/', views.ContactProfileCreate.as_view(),name='profile_contact-add'),
    path('profile_contact_update/<int:id>/', views.ContactProfileUpdate.as_view(), name='profile_contact_update'),
    path('profile_contact_delete/<int:id>/', views.ContactProfileDelete.as_view(), name='profile_contact_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Perfiles Sitio ------------------------------------------------------
    path('profile_site/', views.SiteProfileList.as_view(),name='profile_site'),
    path('profile_site_detail/<int:id>/',views.SiteProfileDetail.as_view(), name='profile_site_detail'),
    path('profile_site-add/', views.SiteProfileCreate.as_view(),name='profile_site-add'),
    path('profile_site_update/<int:id>/', views.SiteProfileUpdate.as_view(), name='profile_site_update'),
    path('profile_site_delete/<int:id>/', views.SiteProfileDelete.as_view(), name='profile_site_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Instrumentos ------------------------------------------------------
    path('instruments/', views.InstrumentsList.as_view(),name='instruments'),
    path('instruments_detail/<int:id>/',views.InstrumentsDetail.as_view(), name='instruments_detail'),
    path('instruments-add/', views.InstrumentsCreate.as_view(),name='instruments-add'),   
    path('instruments_update/<int:id>/', views.InstrumentsUpdate.as_view(), name='instruments_update'),
    path('instruments_delete/<int:id>/', views.InstrumentsDelete.as_view(), name='instruments_delete'),

    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------------------------------------------------------#---------------------------------------- FACTURACIÓN ------------------------------------------------------
    #------------------------------------- CRUD Instrumentos en Sitio------------------------------------------------------
    # path('instruments-site/', views.InstrumentsSiteList.as_view(),
    #      name='instruments-site'),
    # path('instruments-site/', views.InstrumentsSiteList.as_view(),name='instruments-site'),
    # path('instruments-site-add/', views.InstrumentsSiteCreate.as_view(),name='instruments-site-add'),
    # path('instruments-site_update/<int:id>/', views.InstrumentsSiteUpdate.as_view(), name='instruments-site_update'),
    # path('instruments_site_delete/<int:id>/', views.InstrumentsDelete.as_view(), name='instruments_site_delete'),
]

home/urls.py
from django.urls import path
from .views import HomeListView

urlpatterns = [
    path('', HomeListView.as_view(), name = 'home'),
]

alta_data/forms.py
from django.shortcuts import render
from django import forms
from lace_app import models as lace_models


class ClientsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not 'Checkbox' in str(visible.field.widget):
                visible.field.widget.attrs['style'] = 'text-transform:uppercase'

    class Meta:
        model = lace_models.ClienteEmpresa
        fields = (
            'id_empresa',
            'razonsocial',
            'nombrepila',
            )


class CertificateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not 'Checkbox' in str(visible.field.widget):
                visible.field.widget.attrs['style'] = 'text-transform:uppercase'

    class Meta:
        model = lace_models.Certificado
        fields = '__all__'
        widgets = {
            'id_empresa': forms.Select(attrs={'class': 'select-item'}),
        }

class BillingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not 'Checkbox' in str(visible.field.widget):
                visible.field.widget.attrs['style'] = 'text-transform:uppercase'

    class Meta:
        model = lace_models.Facturacion
        fields = (
            'id_empresa',
            'rfc',
            'usocfdi',
            'metodopago',
            'formapago',
            'email',
            'calle',
            'noint',
            'noext',
            'codigopostal',
            'colonia',
            'alcaldia_municipio',
            'entidadfed',
            'pais',
        )
        widgets = {
            'id_empresa': forms.Select(attrs={'class': 'select-item'}),
            'usocfdi': forms.Select(attrs={'class': 'select-item'}),
            'metodopago': forms.Select(attrs={'class': 'select-item'}),
            'formapago': forms.Select(attrs={'class': 'select-item'}),
        }

class ContactProfieForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not 'Checkbox' in str(visible.field.widget):
                visible.field.widget.attrs['style'] = 'text-transform:uppercase'

    class Meta:
        model = lace_models.Contacto
        fields = "__all__"
        widgets = {
            'id_empresa': forms.Select(attrs={'class': 'select-item'}),
        }

class SiteCollectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not 'Checkbox' in str(visible.field.widget):
                visible.field.widget.attrs['style'] = 'text-transform:uppercase'

    class Meta:
        model = lace_models.Sitio
        fields = (
            'id_empresa',
            'telefono',
            'email',
            'calle',
            'noint',
            'noext',
            'codigopostal',
            'colonia',
            'alcaldia_municipio',
            'entidadfed',
            'pais',
        )
        widgets = {
            'id_empresa': forms.Select(attrs={'class': 'select-item'}),
        }


class InstrumentsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        parent = kwargs.pop("parent", None)
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not 'Checkbox' in str(visible.field.widget):
                visible.field.widget.attrs['style'] = 'text-transform:uppercase'
        if parent:
            self.fields['id_sitio'].queryset = lace_models.Sitio.objects.filter(id_empresa= parent)

    class Meta:
        model = lace_models.Instrumento
        fields = (
            'id_empresa',
            'clave_id',
            'areamagnitud',
            'marca',
            'modelo',
            'serie',
            'intervalooperacion',
            'alcance',
            'exactitud',
            'emt',
            'divisionminima',
            'puntoscalibracion',
            'id_sitio',
        )
        widgets = {
            'id_empresa': forms.Select(attrs={'class': 'select-item'}),
            'id_sitio': forms.Select(attrs={'class': 'select-item'}),
            'areamagnitud': forms.SelectMultiple
        }


#---------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------- Formularios para crear Orden de Servicio -------------------------------------------------
#---------------------------------------------------- Test 1 ---------------------------------------------------------------------
class OrdenServicioFormulario1(forms.ModelForm):
    class Meta:
        model = lace_models.OrdenServicio
        fields = {"id_cliente"}
        # widgets = 


class OrdenServicioFormulario2(forms.ModelForm):
    CHOICES_FIELDS = (
        (0, "-------------------"),
        (1, "Servicio en Sitio"),
        (2, "Recolección y Entrega"),
        (3, "Tercería (Subcontratación)"),
    )

    tipo_servicio = forms.ChoiceField(label= "opciones", choices= CHOICES_FIELDS)

    class Meta:
        model = lace_models.SubServicio
        fields = ['id_sitio', 'tipo_servicio']
        # fields = '__all__'
        # widgets = 


class OrdenServicioFormulario3(forms.ModelForm):
    class Meta:
        model = lace_models.SubServicio
        fields = {'id_instrumento'}
        # widgets = 


class OrdenServicioFormulario4(forms.ModelForm):
    class Meta:
        model = lace_models.InstrumentOS
        # fields = 
        exclude = {'id_OSSubServicio', 'id_instrumento'}
        # widgets = 


class OrdenServicioFormulario5(forms.ModelForm):
    class Meta:
        model = lace_models.SubServicio
        fields = {
            'id_facturacion',
            'id_certificado',
        }
        # widgets = 


class OrdenServicioFormulario6(forms.ModelForm):
    class Meta:
        model = lace_models.OrdenServicio
        fields = {
            'dia_servicio',
            'id_contacto',
            'observaciones_os',
        }
        widgets = {
            'dia_servicio': forms.DateTimeInput(attrs={"type": "datetime-local",  "class": "select-item"}),
        }

class ServicioSitioFormulario(forms.ModelForm):
    select_other = forms.ChoiceField(choices= ((1,''),), widget= forms.CheckboxSelectMultiple, label= "Otra Opción")
    class Meta:
        model = lace_models.ServicioSitio
        fields = {
            'epp',
            'epp_option',
            'select_other'
            }


class TerceriaFormulario(forms.ModelForm):
    class Meta:
        model = lace_models.TerceriaSubcontratacion
        fields = ['razonsocial']


class RecoleccionEntregaFormulario(forms.ModelForm):
    class Meta:
        model = lace_models.RecoleccionEntrega
        exclude = ['id_empresa', 'id_sitio']
#---------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------- Formularios para crear Orden de Servicio -------------------------------------------------
#---------------------------------------------------- Test 2 ---------------------------------------------------------------------
class OSFormulario1(forms.ModelForm):
    '''Formulario 1: los campos a llenar en este formulario pertenecen al modelo Orden de Servicio.
    se excluyen los campos "ID_status", "OrdenServicio" y "Día_registro" pues estos campos serán
    llenados automáticamente en el backend.'''

    class Meta:
        model = lace_models.OrdenServicio
        fields = ['id_cliente']
        widgets = {
            'dia_servicio': forms.DateTimeInput(attrs={"type": "datetime-local",  "class": "select-item"}),
        }

    def __init__(self, filter=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if filter != None:
            self.fields['id_cliente'].queryset = lace_models.ClienteEmpresa.objects.filter(id_empresa__contains= filter)

class OSFormulario2(forms.ModelForm):
    '''Formulario 2: los campos de este formulario pertenecen al modelo SubServicio.'''
    class Meta:
        model = lace_models.SubServicio
        exclude = ['id_ordenservicio']

# class OS

templates/alta_data/billing.html
{% extends "../principal/layout.html" %} 
{% load static %}
{% block title %} 
LACE | Facturación
{% endblock %} 
{% block body %}
<main>
  <h2>Perfiles de Facturación</h2>

  <section class="sombra">
    <table id="sort">
      <thead>
        <tr>
          <th>Opciones</th>
          <th class="sort-head">ID Cliente</th>
          <th class="sort-head">RFC</th>
          <th class="sort-head">CFDI</th>         
          <th class="sort-head">Método de pago</th>
          <th class="sort-head">Forma de pago</th>                  
        </tr>
      </thead>
      <tbody>
        {% if facturacion %} 
        {% for facturacion in facturacion %}
        <tr>
          <td>   
            <div class="dropdown button-position">
              <button class="button2 ">
                <i class="material-icons">
                  <span class="material-icons-outlined"> settings </span>
                </i>
                <span class="icon-text"> Opciones </span>
              </button>
              <div class="dropdown-content" style="margin-top:10rem;margin-left: 0rem;">
                <a href="{% url  'alta_data:billing_detail' facturacion.id %}">Detalles</a>
                <a href="{% url  'alta_data:billing_update' facturacion.id %}">Actualizar</a>
                <a href="{% url  'alta_data:billing_delete' facturacion.id %}">Eliminar</a>
              </div>
            </div>
          </td>
          <td>{{facturacion.id_empresa}}</td>            
          <td>{{facturacion.rfc}}</td>
          <td>{{facturacion.usocfdi}}</td>
          <td>{{facturacion.metodopago}}</td>
          <td>{{facturacion.formapago}}</td>                  
        </tr>
        {% endfor%}
      </tbody>

      <!-- If objet_list is empty  -->
      {% else %}
      <p style="color: red">No tienes perfiles para facturación</p>
      {% endif %}
    </table>
    <nav style="display: flex; justify-content: center">
      <a
        href="{% url 'alta_data:billing-add' %}"
        class="button1 button-position"
        >Agregar facturación</a
      >
    </nav>
  </section>
</main>

{% endblock %}

<script src='{% static "js/principal/layout.js" %}'></script>

templates/alta_data/certificate.html
{% extends "../principal/layout.html" %}
{% load static %}
{% block title %} 
LACE | Perfiles de Certificado 
{% endblock %} 
{% block body %}
<main>
  <h2>Perfiles para certificado</h2>
    <table id="sort">
      <thead>
        <tr>
          <th>Opciones</th>
          <th class="sort-head">ID Cliente</th>        
          <th class="sort-head">Razón Social</th>
          <th class="sort-head">Atención</th>
        </tr>
      </thead>
      <tbody>
        {% if certificado %} 
        {% for certificado in certificado %}
        <tr>
          <td>   
            <div class="dropdown button-position">
              <button class="button2 ">
                <i class="material-icons">
                  <span class="material-icons-outlined"> settings </span>
                </i>
                <span class="icon-text"> Opciones </span>
              </button>

              <div class="dropdown-content" style="margin-top:10rem;margin-left: 0rem;">
                <a href="{% url  'alta_data:certificate_detail' certificado.id %}">Detalles</a>
                <a href="{% url  'alta_data:certificate_update' certificado.id %}">Actualizar</a>
                <a href="{% url  'alta_data:certificate_delete' certificado.id %}">Eliminar</a>
              </div>
            </div>
          </td>
          <td>{{certificado.id_empresa}}</td>
          <td>{{certificado.razonsocial}}</td>
          <td>{{certificado.atencion}}</td>
        </tr>
        {% endfor%}
      </tbody>

      <!-- If objet_list is empty  -->
      {% else %}
      <p style="color: red">No tienes perfiles para certificado</p>
      {% endif %}
    </table>
    <nav style="display: flex; justify-content: center">
      <a
        href="{% url 'alta_data:certificate-add' %}"
        class="button1 button-position"
        >Agregar certificado</a
      >
    </nav>
  </section>
</main>

{% endblock %}


<script src='{% static "js//layout.js" %}'></script>principal

templates/alta_data/clients.html
{% extends "../principal/layout.html" %} 
{% load static %}
{% block title %} 
LACE | Clientes 
{%endblock %} 

{% block body %}
<main>
  <h2>Clientes</h2>
  <section class="sombra ">
<div class="row">
<div class="container"> 
      
    <table id="sort">
      <thead>
        <tr>
          <th>Detalles</th>
          <th class="sort-head">ID Cliente</th>
          <th class="sort-head">Razón Social</th>
          <th class="sort-head">Nombre de pila</th>
        </tr>
      </thead>
      <tbody>
        {% if cliente %} 
        {% for cliente in cliente %}
        <tr>
          <td>
      <div class="dropdown button-position">
        <button class="button2 ">
          <i class="material-icons">
            <span class="material-icons-outlined"> settings </span>
          </i>
          <span class="icon-text"> Opciones </span>
        </button>

        <div class="dropdown-content" style="margin-top: 10rem;margin-left: 0rem;">
          <a href="{% url 'alta_data:clients_detail' cliente.id %}">Detalles</a>
          <a href="{% url 'alta_data:clients_update' cliente.id %}">Actualizar</a>
          <a href="{% url 'alta_data:clients_delete' cliente.id %}">Eliminar</a>
        </div>
      </div>
          </td>
          <td>{{cliente.id_empresa}}</td>
          <td>{{cliente.razonsocial}}</td>
          <td>{{cliente.nombrepila}}</td>
        </tr>
        {% endfor%}
      </tbody>

      <!-- If objet_list is empty  -->
      {% else %}
      <p style="color: red">No tienes perfiles de clientes</p>
      {% endif %}
    </table>
    <nav style="display: flex; justify-content: center">
      <a
        href="{% url 'alta_data:clients-add' %}"
        class="button1 button-position"
        >Agregar cliente</a
      >
    </nav>
          </div>
                </div>
  </section>
</main>
{% endblock %}

<script>
  console.log('probando');
  const updateClase = document.querySelectorAll('.container').innerHTML;
  console.log(updateClase);
  console.log(updateClase[0]);
  // enlaces[0].textContent = 'Cambié este texto con JavaScript y te manda a google'
  // enlaces[0].href = "http://google.com";
  // enlaces[0].classList.add('nueva-clase')
  // enlaces[0].classList.remove("nueva-clase");
</script>

templates/alta_data/contact_profile.html
{% extends "../principal/layout.html" %} 
{% block title %} 
LACE | Perfiles de Contacto 
{% endblock %} 
{% block body %}
<main>
  <h2>Perfiles de contacto</h2>

  <section class="sombra">
    <table id="sort">
      <thead>
        <tr>
          <th>Opciones</th>
          <th class="sort-head">Nombre</th>      
          <th class="sort-head">Email</th> 
          <th class="sort-head">Teléfono</th>   
          <th class="sort-head">ID Cliente</th>
          <th class="sort-head">Puesto</th>
        </tr>
      </thead>
      <tbody>
        {% if contacto %} 
        {% for contacto in contacto %}
        <tr>
          <td>   
            <div class="dropdown button-position">
              <button class="button2 ">
                <i class="material-icons">
                  <span class="material-icons-outlined"> settings </span>
                </i>
                <span class="icon-text"> Opciones </span>
              </button>

              <div class="dropdown-content" style="margin-top:10rem;margin-left: 0rem;">
                <a href="{% url 'alta_data:profile_contact_detail' contacto.id %}">Detalles</a>
                <a href="{% url 'alta_data:profile_contact_update' contacto.id %}">Actualizar</a>
                <a href="{% url 'alta_data:profile_contact_delete' contacto.id %}">Eliminar</a>
              </div>
            </div>
          </td>

          <td>{{contacto.nombre}} {{contacto.apellidopaterno}}</td>           
          <td>{{contacto.correo}}</td>
          <td>{{contacto.telefono}}</td>    
          <td>{{contacto.id_empresa}}</td>            
          <td>{{contacto.puesto}}</td>
        </tr>

        {% endfor%}
      </tbody>

      <!-- If objet_list is empty  -->
      {% else %}
      <p style="color: red">No tienes perfiles de contacto</p>
      {% endif %}
    </table>
    <nav style="display: flex; justify-content: center">
      <a
        href="{% url 'alta_data:profile_contact-add' %}"
        class="button1 button-position"
        >Agregar perfil</a
      >
    </nav>
  </section>
</main>

{% endblock %}

templates/alta_data/instruments.html
{% extends "../principal/layout.html" %} 
{% load static %}
{% block title %} 
LACE | Instrumentos
{% endblock %} 
{% block body %}
<main>
  <h2>Instrumentos</h2>
  <section class="sombra">

    <table id="sort">
      <thead>
        <tr>
          <th>Opciones</th>
          <th class="sort-head">ID Cliente</th>
          <th class="sort-head">ID Instrumento</th>
          <th class="sort-head">ID Sitio</th>
          <th class="sort-head">Marca</th>
          <th class="sort-head">Modelo</th>
      </thead>
      <tbody>
        {% if object_list %} 
        {% for object in object_list %}
        <tr>
          <td>
            <div class="dropdown button-position">
              <button class="button2 ">
                <i class="material-icons">
                  <span class="material-icons-outlined"> settings </span>
                </i>
                <span class="icon-text"> Opciones </span>
              </button>

              <div class="dropdown-content" style="margin-top:10rem;margin-left: 0rem;">
                <a href="{% url 'alta_data:instruments_detail' object.id %}">Detalles</a>
                <a href="{% url 'alta_data:instruments_update' object.id %}">Actualizar</a>
                <a href="{% url 'alta_data:instruments_delete' object.id %}">Eliminar</a>
              </div>
            </div>
          </td>
          <td>{{object.id_empresa}}</td>            
          <td>{{object.clave_id}}</td>
          <td>{{object.id_sitio}}</td>         
          <td>{{object.marca}}</td>
          <td>{{object.modelo}}</td>
        </tr>

        {% endfor%}
      </tbody>

      <!-- If objet_list is empty  -->
      {% else %}
      <p style="color: red">No tienes perfiles de contacto</p>
      {% endif %}
    </table>
    <nav style="display: flex; justify-content: center">
      <a
        href="{% url 'alta_data:instruments-add' %}"
        class="button1 button-position"
        >Agregar instrumentos</a
      >
    </nav>
  </section>
</main>

{% endblock %}

<script src='{% static "js//layout.js" %}'></script>principal

templates/alta_data/site_profile.html
{% extends "../principal/layout.html" %} 
{% load static %}
{% block title %} 
LACE | Recolección Entrega
{% endblock %} 
{% block body %}
<main>
  <h2>Recolección entrega</h2>

  <section class="sombra"> 
    <table id="sort">
      <thead>
        <tr>
          <th>Opciones</th>
          <th class="sort-head">ID Cliente</th>
          <th class="sort-head">Teléfono</th>
          <th class="sort-head">Email</th>          
          <th class="sort-head">Alcaldía/Municipio</th>
        </tr>
      </thead>
      <tbody>
        {% if object_list %} 
        {% for object in object_list %}
        <tr>
          <td>
            <div class="dropdown button-position">
              <button class="button2 ">
                <i class="material-icons">
                  <span class="material-icons-outlined"> settings </span>
                </i>
                <span class="icon-text"> Opciones </span>
              </button>

              <div class="dropdown-content" style="margin-top:10rem;margin-left: 0rem;">
                <a href="{% url 'alta_data:profile_site_detail' object.id %}">Detalles</a>
                <a href="{% url 'alta_data:profile_site_update' object.id %}">Actualizar</a>
                <a href="{% url 'alta_data:profile_site_delete' object.id %}">Eliminar</a>
              </div>
            </div>
          </td>
          <td>{{object.id_empresa}}</td>            
          <td>{{object.telefono}}</td>
          <td>{{object.email}}</td>
          <td>{{object.alcaldia_municipio}}</td>
             
        </tr>

        {% endfor%}
      </tbody>

      <!-- If objet_list is empty  -->
      {% else %}
      <p style="color: red">No tienes perfiles de contacto</p>
      {% endif %}
    </table>
    <nav style="display: flex; justify-content: center">
      <a
        href="{% url 'alta_data:profile_site-add' %}"
        class="button1 button-position"
        >Agregar perfil</a
      >
    </nav>
  </section>
</main>

{% endblock %}
<script src='{% static "js/principal/layout.js" %}'></script>

templates/alta_data/site_profile_delete.html
{% extends "../principal/layout.html" %} 

{% block title %}
      LACE | Eliminar sitio
{% endblock %}

{% block body %}
<main>
      <form method="post">
      {% csrf_token %}
      <div>
            <h3 style="color:red">¿Estás seguro que deseas borrar el perfil de {{ object.id_empresa }} ? </h3> 
            <div class="button-position">
                  <input type="submit" value="Eliminar"  class="button1">
            </div>
      </div>
      </form>
      <form action="{% url 'alta_data:profile_site' %}">
            <div class="button-position">
                  <button type="submit" class="button1">Cancelar</button>
            </div>
      </form>
      <section class="sombra">
    <table>
      <thead>
        <tr>
          <th>ID Cliente</th>
          <th>Teléfono</th>
          <th>Email</th>
          <th>Alcaldía/Municipio</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{sitio.id_empresa}}</td>            
          <td>{{sitio.telefono}}</td>
          <td>{{sitio.email}}</td>
          <td>{{sitio.alcaldia_municipio}}</td>
        </tr>
      </tbody>
    </table>
      </section>
</main>

{% endblock %}